version: '3'
services:
  install:
    image: jmfirth/webpack
    command: npm rebuild -q
    volumes:
      - .:/app

  build:
    image: jmfirth/webpack
    command: webpack
    volumes:
      - .:/app

  watch:
    image: jmfirth/webpack
    command: webpack-dev-server --hot --inline --progress --host 0.0.0.0
    volumes:
      - .:/app
    ports:
      - "8080:8080"
